version: '3.7'

#Docker Networks
networks:
  laravel:
    driver: bridge

services:

  #PHP Service
  app:
    build:
      args:
        user: laravel
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: php:fpm
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    depends_on:
      - webserver
      - db
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel

  #Nginx Service
  webserver:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel

  #MySQL Service
  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/db/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel
#Volumes
volumes:
  dbdata:
    driver: local
